/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gestrentelba;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;

/**
 *
 * @author tss
 */
public class JFrameGestRentElba extends javax.swing.JFrame {

    private final ArrayList<Turista> archivioTuristi;
    private final ArrayList<Mezzo> archivioMezzi;
    private final ArrayList<Noleggio> archivioNoleggi;

    /**
     * Creates new form JFrameGestRentElba
     */
    public JFrameGestRentElba() {
        initComponents();
        this.archivioNoleggi = new ArrayList();
        this.archivioTuristi = new ArrayList();
        this.archivioMezzi = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfCognome = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        lCognome = new javax.swing.JLabel();
        jtfUsr = new javax.swing.JTextField();
        jlUsr = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JTextField();
        jllPassword = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jbTurista = new javax.swing.JButton();
        jllTelefono = new javax.swing.JLabel();
        jtfModello = new javax.swing.JTextField();
        jtfCostoOrario = new javax.swing.JTextField();
        jtfAssicurazione = new javax.swing.JTextField();
        jbMoto = new javax.swing.JButton();
        jbBicicletta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNome.setText("Nome");

        lCognome.setText("Cognome");

        jlUsr.setText("User");

        jllPassword.setText("Password");

        jbTurista.setText("Turista");
        jbTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTuristaActionPerformed(evt);
            }
        });

        jllTelefono.setText("Telefono");

        jbMoto.setText("Moto");
        jbMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMotoActionPerformed(evt);
            }
        });

        jbBicicletta.setText("Bicicletta");
        jbBicicletta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBiciclettaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addComponent(jbTurista)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbMoto)
                                                .addGap(18, 18, 18)
                                                .addComponent(jbBicicletta)
                                                .addGap(43, 43, 43))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jllTelefono)
                                                        .addComponent(jlUsr)
                                                        .addComponent(lCognome)
                                                        .addComponent(jllPassword)
                                                        .addComponent(lNome))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jtfCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                                                .addComponent(jtfModello, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jtfUsr, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jtfPassword)
                                                                                        .addComponent(jtfNome))
                                                                                .addGap(101, 101, 101)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jtfCostoOrario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jtfAssicurazione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lNome)
                                        .addComponent(jtfCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lCognome)
                                        .addComponent(jtfCostoOrario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlUsr)
                                        .addComponent(jtfUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfAssicurazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jllPassword))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jllTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbTurista)
                                        .addComponent(jbMoto)
                                        .addComponent(jbBicicletta))
                                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGestRentElba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGestRentElba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGestRentElba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGestRentElba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGestRentElba().setVisible(true);
            }
        });
    }

    private void jbTuristaActionPerformed(java.awt.event.ActionEvent evt) {
        String nome = jtfNome.getText();
        String cognome = jtfCognome.getText();
        String usr = jtfUsr.getText();
        String password = jtfPassword.getText();
        String telefono = jtfTelefono.getText();
        archivioTuristi.add(new Turista(usr, password, nome, cognome, "indirizzo", 0, telefono));
        jtfNome.setText("");
        jtfCognome.setText("");
        jtfUsr.setText("");
        jtfPassword.setText("");
        jtfTelefono.setText("");
    }

    private void jbMotoActionPerformed(java.awt.event.ActionEvent evt) {
        String modello = jtfModello.getText();
        String costoOrario = jtfCostoOrario.getText();
        String assicurazione = jtfAssicurazione.getText();
        archivioMezzi.add(new Motocicletta(modello, Float.parseFloat(costoOrario), Float.parseFloat(assicurazione)));
        jtfModello.setText("");
        jtfCostoOrario.setText("");
        jtfAssicurazione.setText("");

    }

    private void jbBiciclettaActionPerformed(java.awt.event.ActionEvent evt) {
        String modello = jtfModello.getText();
        String costoOrario = jtfCostoOrario.getText();
        archivioMezzi.add(new Bicicletta(modello, Float.parseFloat(costoOrario)));
        jtfModello.setText("");
        jtfCostoOrario.setText("");
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbBicicletta;
    private javax.swing.JButton jbMoto;
    private javax.swing.JButton jbTurista;
    private javax.swing.JLabel jlUsr;
    private javax.swing.JLabel jllPassword;
    private javax.swing.JLabel jllTelefono;
    private javax.swing.JTextField jtfAssicurazione;
    private javax.swing.JTextField jtfCognome;
    private javax.swing.JTextField jtfCostoOrario;
    private javax.swing.JTextField jtfModello;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfTelefono;
    private javax.swing.JTextField jtfUsr;
    private javax.swing.JLabel lCognome;
    private javax.swing.JLabel lNome;
    // End of variables declaration     

    /**
     * Ritorna le informazioni essenziali per capire "chi ha noleggiato cosa"
     *
     * @param indice
     *
     */
    private SchedaNoleggio reportNoleggioMezzo(int indice) {
        SchedaNoleggio schedaNoleggio;
        float noleggio = 0f;

        schedaNoleggio = new SchedaNoleggio(archivioNoleggi.get(indice).getMezzo().getModello());
        schedaNoleggio.setCognome(archivioNoleggi.get(indice).getTurista().getCognome());
        schedaNoleggio.setNome(archivioNoleggi.get(indice).getTurista().getNome());
        schedaNoleggio.setIndirizzo(archivioNoleggi.get(indice).getTurista().getIndirizzo());
        schedaNoleggio.setTelefono(archivioNoleggi.get(indice).getTurista().getTelefono());
        if (archivioNoleggi.get(indice).getFineNoleggio() != null) {
            noleggio = calcolaCosto(archivioNoleggi.get(indice).getInizioNoleggio().truncatedTo(ChronoUnit.HOURS),
                    archivioNoleggi.get(indice).getFineNoleggio().truncatedTo(ChronoUnit.HOURS),
                    archivioNoleggi.get(indice).getMezzo().getModello(),
                    archivioNoleggi.get(indice).getMezzo().getPrezzoDay(),
                    archivioNoleggi.get(indice).getMezzo().getPrezzoOra());
        }
        schedaNoleggio.setCostoNoleggio(noleggio);
        return schedaNoleggio;
    }

    private float calcolaCosto(LocalDateTime inizioNoleggio, LocalDateTime fineNoleggio, String modello, Float prezzoDay, Float prezzoOra) {
        float costo = 0;

        // da fare   
        return costo;
    }
}
